package it.polimi.ingsw.client.GUI;

public enum StateOfGUI {

    INSERTNAME, CHANGENAME, LOADINGMATCH, MASTERSELECTNUMBEROFPLAYERS, CHOOSECOLOR, WAITINGOTHERPLAYERSCHOOSE,
    MASTERCHOOSECARD, PLAYERCHOOSECARD, STARTNORMALGAME,
}
