package it.polimi.ingsw.client.GUI;

public enum StateOfGUI {

    INSERTNAME, CHANGENAME, LOADINGMATCH, MASTERSELECTNUMBEROFPLAYERS, MASTERCHOOSECOLOR, PLAYERCHOOSECOLOR, WAITINGOTHERPLAYERSCHOOSE,
    MASTERCHOOSECARD, PLAYERCHOOSECARD, STARTNORMALGAME
}
